# Generated by Django 5.0.4 on 2024-04-07 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoTotal',
            fields=[
                ('id_saldo_total', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_totalcol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TablaBalanceGeneral',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=45)),
                ('concepto', models.CharField(max_length=100)),
                ('inversion', models.FloatField(null=True)),
                ('ingresos_a_caja', models.FloatField(null=True)),
                ('prestamo', models.FloatField(null=True)),
                ('cobros', models.FloatField(null=True)),
                ('creditos', models.FloatField(null=True)),
                ('renovaciones', models.FloatField(null=True)),
                ('salarios', models.FloatField(null=True)),
                ('prestamos_trabajadores', models.FloatField(null=True)),
                ('salidas', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TablaRutas',
            fields=[
                ('id_tabla_rutas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('nombre_trabajador', models.CharField(max_length=45, null=True)),
                ('tipo_ruta', models.CharField(max_length=45, null=True)),
                ('cantidad', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TablaCreditos',
            fields=[
                ('id_creditos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('id_tabla_general', models.IntegerField(null=True)),
                ('tipo_credito', models.CharField(max_length=45, null=True)),
                ('cantidad', models.FloatField(null=True)),
                ('tabla_balance_general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TorogozApp.tablabalancegeneral')),
            ],
        ),
        migrations.CreateModel(
            name='TablaRenovaciones',
            fields=[
                ('id_renovaciones', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('id_tabla_general', models.IntegerField(null=True)),
                ('tipo_renovacion', models.CharField(max_length=45, null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('tabla_balance_general', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TorogozApp.tablabalancegeneral')),
            ],
        ),
    ]
