# Generated by Django 5.0.4 on 2024-04-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TorogozApp', '0002_remove_tablacreditos_tabla_balance_general_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablacreditos',
            old_name='id_tabla_general',
            new_name='tabla_general',
        ),
        migrations.RenameField(
            model_name='tablarenovaciones',
            old_name='id_tabla_general',
            new_name='tabla_general',
        ),
    ]
